args: !!python/object:argparse.Namespace
  batch_size: 64
  conv_type: GINE
  dataset: /cta/users/vkaya/gnn/matrix/hic_4DNFIBM9QCFG_nMax51_nMin31_perc10
  dropout: 0.0
  edge_margin: 0.15
  env: slurm
  hidden_dim: 128
  input_dim: 2
  lr: 0.001
  margin: 0.1
  max_size_Q: 41
  max_size_T: 51
  min_size: 31
  n_devices: 1
  n_epoch: 20
  n_layers: 3
  n_nodes: 1
  n_workers: 14
  opt: adam
  opt_decay_rate: null
  opt_decay_step: null
  opt_restart: 100
  opt_scheduler: cos
  save_path: ./experiments
  steps_per_test: 24
  steps_per_train: 5000
  steps_per_val: 24
  tag: '3'
  weight_decay: 0.0
